# Generated by Django 2.1.3 on 2019-01-18 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=50, verbose_name='联系方式')),
                ('desc', models.CharField(max_length=200, verbose_name='个人签名')),
                ('uuid', models.CharField(max_length=100, verbose_name='用户标识')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '普通用户',
                'verbose_name_plural': '普通用户',
            },
        ),
    ]
