# Generated by Django 2.1.3 on 2019-01-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_otheruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otheruser',
            name='uuid',
            field=models.CharField(default='b39106b1cf454e7a85547ca0035cfd38', max_length=100, verbose_name='用户标识'),
        ),
    ]
